### ISSUE TITLE
Document for app.settings

### ISSUE THREAD

**Issue by asg-code** [mrochon/b2c-mt-rest#1]
Hello,

I am trying to use your samples in my application. Is there any documentation for the app setting values that would help me specify values particular to me. Things like, where does the values for AuthCert, ClientCreds etc. come from or what should I be putting in there. I would like to setup this service with a new namespace and in my instance of Azure with my certs etc.

Any help or pointers would be much appreciated.

Thank you.

**Comment by mrochon** [comment]
The B2C samples repo contains the scripts which use both this repo and mt_webapp to set up a multitenant app. Let me know if that does not resolve this for you.

**Comment by mrochon** [comment]
Sorry, meant to b2c_samples...

**Comment by asg-code** [comment]
Thank you for the quick reply. Yes, I am following the documentation there. So far I have been able to setup by B2C, build the REST service locally, build the asp.net locally. Now I am trying to set up the REST api service and deploy to Azure via DevOps CI/CD pipeline, and hence the questions. Does the setup script (Setup-B2CMultiTenant.ps1) update this settings file (app.settings.json)?

My ultimate goals is to use DevOps CI/CD to setup by services and other code elements and ARM templates (if possible) to setup the directory and policies.

Once again, thank you for your great samples that are extremely helpful.

**Comment by mrochon** [comment]
Yes, the Power Shell script updates the Azure service config. You should be able to run the app after completing the script.

**Comment by mrochon** [comment]
This repo is used by b2csamples scripts. See all docs there.
